name: Production Seed

on:
  push:
    branches: [ main ]

jobs:
  seed-production:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Wait for Vercel Production Deployment
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: vercel-production
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 900
        environment: production
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run production seed script
      env:
        NEXT_PUBLIC_APP_URL: ${{ steps.vercel-production.outputs.url }}
        NEXT_PUBLIC_ENVIRONMENT: prod
        MONGODB_URI: ${{ secrets.PRODUCTION_MONGODB_URI }}
        JWT_PRIVATE_KEY: ${{ secrets.PRODUCTION_JWT_PRIVATE_KEY }}
        JWT_PUBLIC_KEY: ${{ secrets.PRODUCTION_JWT_PUBLIC_KEY }}
        BASE_USER_PASSWORDS_MAP: ${{ secrets.PRODUCTION_BASE_USER_PASSWORDS_MAP }}
      run: npm run seed